Update LoggingTrainingListener.java
Fixed incorrect metric name that may cause the following exception:
java.lang.IllegalArgumentException: Metric name not found: epoch